# Site settings
title: Zork Networks
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zorknet.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
